### ISSUE TITLE
Demo Link shows 404

### ISSUE THREAD

**Issue by geoffreyyip** [dime-worldbank/quarto-dime-theme#4]
README lists https://bbieri.github.io/quartoDIMEtheme as a demo. However, the link goes to a 404 page

**Comment by kbjarkefur** [comment]
Thank you for bringing this to our attention. We had not updated the links since this repo was moved to the DIME account. The correct link his here: https://dime-worldbank.github.io/quarto-dime-theme/

**Comment by kbjarkefur** [comment]
@geoffreyyip , thanks to you I found several outdated links. The updated version of the repo can be found in this branch: https://github.com/dime-worldbank/quarto-dime-theme/tree/update-account. Use that if you need this template right now. After these changes are reviewed we will merge them to the main branch.

**Comment by BBieri** [comment]
Thanks for preparing a PR @kbjarkefur! I will go over the changes over the weekend.

**Comment by BBieri** [comment]
Everything looks good on my side @kbjarkefur. I have made some more fixes to links and updated the README. I also created a new PR to merge changes from develop onto main to rebuild the demo website.
