### ISSUE TITLE
Links in footer in demo does not work despite being correct

### ISSUE THREAD

**Issue by kbjarkefur** [dime-worldbank/quarto-dime-theme#7]
All links in the presentation opens up in a browser window in the presentation. Is this something that can be toggled on and off? 

This within-presentation browser does not seem to work for the links in the footer. When I click any of the links in the footer in the demo presentation, I get this view and the link does not open:

![image](https://github.com/dime-worldbank/quarto-dime-theme/assets/15911801/0fb78c83-ac7b-403c-a275-ad6539437b7e)

When I try opening a link in the footer, I get this message in the console: 

> Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

**Comment by BBieri** [comment]
Thanks for reporting and testing the template :)
I've opened up a PR changing the default setting that opens previews of links within the presentation to directly opening them in a new tab.
